/**
 * This file was auto-generated by the MCP Agent based on the OpenAPI specification.
 * Trimmed to include only types for /run, /run_sse, and /sessions/{id} endpoints.
 */

// --- Root Request/Response Types ---

/**
 * Request body for `POST /run` and `POST /run_sse`
 *
 * Required fields:
 * - appName: string
 * - userId: string
 * - sessionId: string
 * - newMessage: AgentContentInput
 *
 * Optional fields:
 * - streaming: boolean
 * - stateDelta: Record<string, unknown> | null
 * - invocationId: string | null
 */
export interface RunAgentRequest {
	appName: string;
	userId: string;
	sessionId: string;
	newMessage: AgentContentInput;
	streaming?: boolean;
	stateDelta?: Record<string, unknown> | null;
	invocationId?: string | null;
}

/**
 * Request body for `PATCH /apps/{app_name}/users/{user_id}/sessions/{session_id}`
 */
export interface UpdateSessionRequest {
	stateDelta: Record<string, unknown>;
}

/**
 * Request body for `POST /apps/{app_name}/users/{user_id}/sessions/{session_id}` (Create Session With Id)
 * This corresponds to the `State` type in the OpenAPI spec (any object).
 */
export type CreateSessionWithIdRequest = Record<string, unknown>;

/**
 * Response for:
 * - `GET /apps/{app_name}/users/{user_id}/sessions/{session_id}`
 * - `POST /apps/{app_name}/users/{user_id}/sessions/{session_id}`
 * - `PATCH /apps/{app_name}/users/{user_id}/sessions/{session_id}`
 */
export interface AgentSession {
	id: string;
	appName: string;
	userId: string;
	state?: Record<string, unknown>;
	events?: AgentEvent[];
	lastUpdateTime?: number;
}

/**
 * Response for `GET /apps/{app_name}/users/{user_id}/sessions`
 * Returns an array of all sessions for a specific user within an application.
 * Each session contains the session ID, app name, user ID, state, events, and last update time.
 */
export type ListSessionsResponse = AgentSession[];

// --- Artifact API Types ---

/**
 * Path parameters for listing artifact names.
 * Used for route: `GET /apps/{app_name}/users/{user_id}/sessions/{session_id}/artifacts`
 */
export interface ListArtifactNamesPathParams {
	appName: string;
	userId: string;
	sessionId: string;
}

/**
 * Path parameters for artifact endpoints.
 * Used for routes: `/apps/{app_name}/users/{user_id}/sessions/{session_id}/artifacts/...`
 */
export interface ArtifactPathParams extends ListArtifactNamesPathParams {
	appName: string;
	userId: string;
	sessionId: string;
	artifactName: string;
}

/**
 * Path parameters for artifact version endpoints.
 * Used for routes: `.../artifacts/{artifact_name}/versions/{version_id}`
 */
export interface ArtifactVersionPathParams extends ArtifactPathParams {
	versionId: number;
}

/**
 * Response for `GET /apps/{app_name}/users/{user_id}/sessions/{session_id}/artifacts/{artifact_name}`
 * Returns the latest version of the artifact as a Part, or null if not found.
 */
export type LoadArtifactResponse = ArtifactPart | null;

/**
 * Response for `DELETE /apps/{app_name}/users/{user_id}/sessions/{session_id}/artifacts/{artifact_name}`
 * Returns an empty object on successful deletion.
 */
export type DeleteArtifactResponse = Record<string, never>;

/**
 * Response for `GET /apps/{app_name}/users/{user_id}/sessions/{session_id}/artifacts/{artifact_name}/versions/{version_id}`
 * Returns a specific version of the artifact as a Part, or null if not found.
 */
export type LoadArtifactVersionResponse = ArtifactPart | null;

/**
 * Response for `GET /apps/{app_name}/users/{user_id}/sessions/{session_id}/artifacts`
 * Returns an array of artifact names for the session.
 */
export type ListArtifactNamesResponse = string[];

/**
 * Response for `GET /apps/{app_name}/users/{user_id}/sessions/{session_id}/artifacts/{artifact_name}/versions`
 * Returns an array of version IDs (integers) for the specified artifact.
 */
export type ListArtifactVersionsResponse = number[];

/**
 * Part type for artifact content (output format).
 * Represents the content of an artifact, which can be text, inline data, file data, etc.
 */
export interface ArtifactPart {
	videoMetadata?: VideoMetadata | null;
	thought?: boolean | null;
	inlineData?: Blob | null;
	fileData?: FileData | null;
	thoughtSignature?: string | null;
	functionCall?: FunctionCall | null;
	codeExecutionResult?: CodeExecutionResult | null;
	executableCode?: ExecutableCode | null;
	functionResponse?: FunctionResponse | null;
	text?: string | null;
}

// --- Event & Content Types ---

/**
 * Represents an event in the agent interaction stream.
 * Response item for `POST /run` (array) and `POST /run_sse` (streamed).
 */
export interface AgentEvent {
	modelVersion?: string | null;
	content?: AgentContent | null;
	groundingMetadata?: GroundingMetadata | null;
	partial?: boolean | null;
	turnComplete?: boolean | null;
	finishReason?: FinishReason | null;
	errorCode?: string | null;
	errorMessage?: string | null;
	interrupted?: boolean | null;
	customMetadata?: Record<string, unknown> | null;
	usageMetadata?: UsageMetadata | null;
	liveSessionResumptionUpdate?: LiveServerSessionResumptionUpdate | null;
	inputTranscription?: Transcription | null;
	outputTranscription?: Transcription | null;
	avgLogprobs?: number | null;
	logprobsResult?: LogprobsResult | null;
	cacheMetadata?: CacheMetadata | null;
	citationMetadata?: CitationMetadata | null;
	invocationId?: string;
	author: string;
	actions?: AgentEventActions;
	longRunningToolIds?: string[] | null;
	branch?: string | null;
	id?: string;
	timestamp?: number;
}

export interface AgentContent {
	parts?: AgentContentPart[] | null;
	role?: string | null;
}

export interface AgentContentPart {
	videoMetadata?: VideoMetadata | null;
	thought?: boolean | null;
	inlineData?: Blob | null;
	fileData?: FileData | null;
	thoughtSignature?: string | null;
	functionCall?: FunctionCall | null;
	codeExecutionResult?: CodeExecutionResult | null;
	executableCode?: ExecutableCode | null;
	functionResponse?: FunctionResponse | null;
	text?: string | null;
}

export interface AgentContentInput {
	parts?: AgentContentPartInput[] | null;
	role?: string | null;
}

export interface AgentContentPartInput {
	videoMetadata?: VideoMetadata | null;
	thought?: boolean | null;
	inlineData?: Blob | null;
	fileData?: FileData | null;
	thoughtSignature?: string | null;
	functionCall?: FunctionCall | null;
	codeExecutionResult?: CodeExecutionResult | null;
	executableCode?: ExecutableCode | null;
	functionResponse?: FunctionResponseInput | null;
	text?: string | null;
}

// --- Shared Data Structures ---

export interface Blob {
	displayName?: string | null;
	data: string;
	mimeType: string;
}

export interface FileData {
	displayName?: string | null;
	fileUri: string;
	mimeType: string;
}

export interface VideoMetadata {
	fps?: number | null;
	endOffset?: string | null;
	startOffset?: string | null;
}

export interface FunctionCall {
	id?: string | null;
	args?: Record<string, unknown> | null;
	name: string;
}

export interface CodeExecutionResult {
	outcome: Outcome | null;
	output?: string | null;
}

export interface ExecutableCode {
	code: string;
	language: Language;
}

export interface FunctionResponseInput {
	willContinue?: boolean | null;
	scheduling?: FunctionResponseScheduling | null;
	parts?: FunctionResponsePart[] | null;
	id?: string | null;
	name: string;
	response: Record<string, unknown>;
}

export interface FunctionResponse {
	willContinue?: boolean | null;
	scheduling?: FunctionResponseScheduling | null;
	parts?: FunctionResponsePart[] | null;
	id?: string | null;
	name: string;
	response: Record<string, unknown>;
}

export interface FunctionResponsePart {
	inlineData?: FunctionResponseBlob | null;
	fileData?: FunctionResponseFileData | null;
}

export interface FunctionResponseBlob {
	mimeType: string;
	data: string;
}

export interface FunctionResponseFileData {
	fileUri: string;
	mimeType: string;
}

export interface GroundingMetadata {
	googleMapsWidgetContextToken?: string | null;
	groundingChunks?: GroundingChunk[] | null;
	groundingSupports?: GroundingSupport[] | null;
	retrievalMetadata?: RetrievalMetadata | null;
	retrievalQueries?: string[] | null;
	searchEntryPoint?: SearchEntryPoint | null;
	sourceFlaggingUris?: GroundingMetadataSourceFlaggingUri[] | null;
	webSearchQueries?: string[] | null;
}

export interface GroundingChunk {
	maps?: GroundingChunkMaps | null;
	retrievedContext?: GroundingChunkRetrievedContext | null;
	web?: GroundingChunkWeb | null;
}

export interface GroundingChunkMaps {
	placeAnswerSources?: GroundingChunkMapsPlaceAnswerSources | null;
	placeId?: string | null;
	text?: string | null;
	title?: string | null;
	uri?: string | null;
}

export interface GroundingChunkMapsPlaceAnswerSources {
	flagContentUri?: string | null;
	reviewSnippets?: GroundingChunkMapsPlaceAnswerSourcesReviewSnippet[] | null;
}

export interface GroundingChunkMapsPlaceAnswerSourcesReviewSnippet {
	authorAttribution?: GroundingChunkMapsPlaceAnswerSourcesAuthorAttribution | null;
	flagContentUri?: string | null;
	googleMapsUri?: string | null;
	relativePublishTimeDescription?: string | null;
	review?: string | null;
	reviewId?: string | null;
	title?: string | null;
}

export interface GroundingChunkMapsPlaceAnswerSourcesAuthorAttribution {
	displayName?: string | null;
	photoUri?: string | null;
	uri?: string | null;
}

export interface GroundingChunkRetrievedContext {
	documentName?: string | null;
	ragChunk?: RagChunk | null;
	text?: string | null;
	title?: string | null;
	uri?: string | null;
}

export interface RagChunk {
	pageSpan?: RagChunkPageSpan | null;
	text?: string | null;
}

export interface RagChunkPageSpan {
	firstPage?: number | null;
	lastPage?: number | null;
}

export interface GroundingChunkWeb {
	domain?: string | null;
	title?: string | null;
	uri?: string | null;
}

export interface GroundingSupport {
	confidenceScores?: number[] | null;
	groundingChunkIndices?: number[] | null;
	segment?: Segment | null;
}

export interface Segment {
	endIndex?: number | null;
	partIndex?: number | null;
	startIndex?: number | null;
	text?: string | null;
}

export interface RetrievalMetadata {
	googleSearchDynamicRetrievalScore?: number | null;
}

export interface SearchEntryPoint {
	renderedContent?: string | null;
	sdkBlob?: string | null;
}

export interface GroundingMetadataSourceFlaggingUri {
	flagContentUri?: string | null;
	sourceId?: string | null;
}

export interface UsageMetadata {
	cacheTokensDetails?: ModalityTokenCount[] | null;
	cachedContentTokenCount?: number | null;
	candidatesTokenCount?: number | null;
	candidatesTokensDetails?: ModalityTokenCount[] | null;
	promptTokenCount?: number | null;
	promptTokensDetails?: ModalityTokenCount[] | null;
	thoughtsTokenCount?: number | null;
	toolUsePromptTokenCount?: number | null;
	toolUsePromptTokensDetails?: ModalityTokenCount[] | null;
	totalTokenCount?: number | null;
	trafficType?: TrafficType | null;
}

export interface ModalityTokenCount {
	modality?: MediaModality | null;
	tokenCount?: number | null;
}

export interface LiveServerSessionResumptionUpdate {
	newHandle?: string | null;
	resumable?: boolean | null;
	lastConsumedClientMessageIndex?: number | null;
}

export interface Transcription {
	text?: string | null;
	finished?: boolean | null;
}

export interface LogprobsResult {
	chosenCandidates?: LogprobsResultCandidate[] | null;
	topCandidates?: LogprobsResultTopCandidates[] | null;
}

export interface LogprobsResultCandidate {
	logProbability?: number | null;
	token?: string | null;
	tokenId?: number | null;
}

export interface LogprobsResultTopCandidates {
	candidates?: LogprobsResultCandidate[] | null;
}

export interface CacheMetadata {
	cache_name?: string | null;
	expire_time?: number | null;
	fingerprint: string;
	invocations_used?: number | null;
	contents_count: number;
	created_at?: number | null;
}

export interface CitationMetadata {
	citations?: Citation[] | null;
}

export interface Citation {
	endIndex?: number | null;
	license?: string | null;
	publicationDate?: GoogleTypeDate | null;
	startIndex?: number | null;
	title?: string | null;
	uri?: string | null;
}

export interface GoogleTypeDate {
	day?: number | null;
	month?: number | null;
	year?: number | null;
}

export interface AgentEventActions {
	skipSummarization?: boolean | null;
	stateDelta?: Record<string, unknown>;
	artifactDelta?: Record<string, number>;
	transferToAgent?: string | null;
	escalate?: boolean | null;
	requestedAuthConfigs?: Record<string, AuthConfig>;
	requestedToolConfirmations?: Record<string, ToolConfirmation>;
	compaction?: EventCompaction | null;
	endOfAgent?: boolean | null;
	agentState?: Record<string, unknown> | null;
	rewindBeforeInvocationId?: string | null;
}

export interface AuthConfig {
	authScheme: APIKey | HTTPBase | OAuth2 | OpenIdConnect | HTTPBearer | OpenIdConnectWithConfig;
	rawAuthCredential?: AuthCredential | null;
	exchangedAuthCredential?: AuthCredential | null;
	credentialKey?: string | null;
	[key: string]: unknown;
}

export interface APIKey {
	type?: SecuritySchemeType;
	description?: string | null;
	in: APIKeyIn;
	name: string;
	[key: string]: unknown;
}

export interface HTTPBase {
	type?: SecuritySchemeType;
	description?: string | null;
	scheme: string;
	[key: string]: unknown;
}

export interface OAuth2 {
	type?: SecuritySchemeType;
	description?: string | null;
	flows: OAuthFlows;
	[key: string]: unknown;
}

export interface OAuthFlows {
	implicit?: OAuthFlowImplicit | null;
	password?: OAuthFlowPassword | null;
	clientCredentials?: OAuthFlowClientCredentials | null;
	authorizationCode?: OAuthFlowAuthorizationCode | null;
	[key: string]: unknown;
}

export interface OAuthFlowImplicit {
	refreshUrl?: string | null;
	scopes?: Record<string, string>;
	authorizationUrl: string;
	[key: string]: unknown;
}

export interface OAuthFlowPassword {
	refreshUrl?: string | null;
	scopes?: Record<string, string>;
	tokenUrl: string;
	[key: string]: unknown;
}

export interface OAuthFlowClientCredentials {
	refreshUrl?: string | null;
	scopes?: Record<string, string>;
	tokenUrl: string;
	[key: string]: unknown;
}

export interface OAuthFlowAuthorizationCode {
	refreshUrl?: string | null;
	scopes?: Record<string, string>;
	authorizationUrl: string;
	tokenUrl: string;
	[key: string]: unknown;
}

export interface OpenIdConnect {
	type?: SecuritySchemeType;
	description?: string | null;
	openIdConnectUrl: string;
	[key: string]: unknown;
}

export interface HTTPBearer {
	type?: SecuritySchemeType;
	description?: string | null;
	scheme?: 'bearer';
	bearerFormat?: string | null;
	[key: string]: unknown;
}

export interface OpenIdConnectWithConfig {
	type?: SecuritySchemeType;
	description?: string | null;
	authorization_endpoint: string;
	token_endpoint: string;
	userinfo_endpoint?: string | null;
	revocation_endpoint?: string | null;
	token_endpoint_auth_methods_supported?: string[] | null;
	grant_types_supported?: string[] | null;
	scopes?: string[] | null;
	[key: string]: unknown;
}

export interface AuthCredential {
	authType: AuthCredentialTypes;
	resourceRef?: string | null;
	apiKey?: string | null;
	http?: HttpAuth | null;
	serviceAccount?: ServiceAccount | null;
	oauth2?: OAuth2Auth | null;
	[key: string]: unknown;
}

export interface HttpAuth {
	scheme: string;
	credentials: HttpCredentials;
	[key: string]: unknown;
}

export interface HttpCredentials {
	username?: string | null;
	password?: string | null;
	token?: string | null;
	[key: string]: unknown;
}

export interface ServiceAccount {
	serviceAccountCredential?: ServiceAccountCredential | null;
	scopes: string[];
	useDefaultCredential?: boolean | null;
	[key: string]: unknown;
}

export interface ServiceAccountCredential {
	type?: string;
	projectId: string;
	privateKeyId: string;
	privateKey: string;
	clientEmail: string;
	clientId: string;
	authUri: string;
	tokenUri: string;
	authProviderX509CertUrl: string;
	clientX509CertUrl: string;
	universeDomain: string;
	[key: string]: unknown;
}

export interface OAuth2Auth {
	clientId?: string | null;
	clientSecret?: string | null;
	authUri?: string | null;
	state?: string | null;
	redirectUri?: string | null;
	authResponseUri?: string | null;
	authCode?: string | null;
	accessToken?: string | null;
	refreshToken?: string | null;
	expiresAt?: number | null;
	expiresIn?: number | null;
	audience?: string | null;
	[key: string]: unknown;
}

export interface ToolConfirmation {
	hint?: string;
	confirmed?: boolean;
	payload?: unknown | null;
}

export interface EventCompaction {
	startTimestamp: number;
	endTimestamp: number;
	compactedContent: AgentContent;
}

// --- Enums and Types ---

export type FinishReason =
	| 'FINISH_REASON_UNSPECIFIED'
	| 'STOP'
	| 'MAX_TOKENS'
	| 'SAFETY'
	| 'RECITATION'
	| 'LANGUAGE'
	| 'OTHER'
	| 'BLOCKLIST'
	| 'PROHIBITED_CONTENT'
	| 'SPII'
	| 'MALFORMED_FUNCTION_CALL'
	| 'IMAGE_SAFETY'
	| 'UNEXPECTED_TOOL_CALL'
	| 'IMAGE_PROHIBITED_CONTENT'
	| 'NO_IMAGE';

export type FunctionResponseScheduling =
	| 'SCHEDULING_UNSPECIFIED'
	| 'SILENT'
	| 'WHEN_IDLE'
	| 'INTERRUPT';

export type Outcome =
	| 'OUTCOME_UNSPECIFIED'
	| 'OUTCOME_OK'
	| 'OUTCOME_FAILED'
	| 'OUTCOME_DEADLINE_EXCEEDED';

export type Language = 'LANGUAGE_UNSPECIFIED' | 'PYTHON';

export type MediaModality =
	| 'MODALITY_UNSPECIFIED'
	| 'TEXT'
	| 'IMAGE'
	| 'VIDEO'
	| 'AUDIO'
	| 'DOCUMENT';

export type TrafficType = 'TRAFFIC_TYPE_UNSPECIFIED' | 'ON_DEMAND' | 'PROVISIONED_THROUGHPUT';

export type SecuritySchemeType = 'apiKey' | 'http' | 'oauth2' | 'openIdConnect';

export type APIKeyIn = 'query' | 'header' | 'cookie';

export type AuthCredentialTypes = 'apiKey' | 'http' | 'oauth2' | 'openIdConnect' | 'serviceAccount';
